### ISSUE TITLE
Can we please see a (functional React) example showing how to set fallbackFocus a dialog's container?

### ISSUE THREAD

**Issue by oddjones** [focus-trap/focus-trap-react#127]
I haven't had much exposure to classic (class based) React, and I'm trying to create a reusable dialog component which makes use of a FocusTrap using this component. I have the FocusTrap as a wrapper around my `<Dialog/>` but can't figure out how to set the fallBackFocus attribute of the focusTrap to my `<Dialog>` (which is a styled div) - can anybody help?

**Comment by stefcameron** [comment]
@oddjones True that this repo doesn't have a functional React component example. I exclusively use functional React components, and also use `focus-trap-react` for a dialog component in the design system I'm building at work.

The good news is, it's very similar to the class-based example in the README.

```jsx
const Dialog = function () {
  <FocusTrap
    focusTrapOptions={{
      fallbackFocus: '#dialog'
    }}
  >
    <div id="dialog" tabIndex="-1">
      <p>Hello</p>
    </div>
  </FocusTrap>
};
```

Rendering the functional component above should result in the `<div>` getting initial focus.

BTW, you may want to use the `initialFocus` option instead of `fallbackFocus` since the latter will only come into effect if `focus-trap` doesn't find any other tabbable (and therefore focusable) node inside the trap. `initialFocus` is more imperative than `fallbackFocus`. That could be your issue as well.

If I changed the above component to have `<button>Hello</button>` (which is focusable and tabbable by default) instead of the `<p>` (with is neither), then the button would always get focus instead of the `<div>` itself -- with the `fallbackFocus` option. But if you replace `fallbackFocus` with `initialFocus`, then the `<div>` should always get focus first...

**Comment by oddjones** [comment]
Many thanks for your reply Stephan. I got as far as recognising that I
could pass in an id (and even added the uuid repo to my code to ensure the
id was always genuine and allowed me to have multiple closed dialogs in my
page if I wanted) - this worked up to a point, but I found I was still
getting multiple errors from within focus-trap itself if I wanted to
implement the trap on a dialog with a slow fade-in. (Something to do with
the focus trap being instantiated before the focusable elements of the
dialog existed is my guess). At this point I gave up and implemented
react-focus-lock which simply worked first time - probably less
configuration options, but nice and easy for me :-)

**Comment by stefcameron** [comment]
My pleasure! I'm glad you found something that works. Sad it's not `focus-trap-react`, of course, but glad you solved your problem. 🎉 

It's definitely tricky when the initial node to focus doesn't exist at the time you create the trap, although `focus-trap` does [have a delay](https://github.com/focus-trap/focus-trap/blob/master/index.js#L144-L146) before it attempts to set focus to the initial node (`delayInitialFocus` is `true` by default when you don't set it explicitly).
