### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by diesel167** [focus-trap/focus-trap-react#1295]
I have a variable component ChildClass as a Modal component child to show different modals.
```
<Modal>
  <ChildClass/>
</Modal>
```
Then i wrapped ChildClass in FocusTrap:
```
<Modal>
  <FocusTrap>
    <ChildClass/>
  </FocusTrap>
</Modal>
```
And nothing is changed. Focus is not trapped.

**Comment by sant123** [comment]
Did you check the console? Perhaps there is an error there

**Comment by stefcameron** [comment]
@diesel167 Thanks for reaching out! Are you able to reproduce this in a code sandbox with minimal code? It might help isolate the issue.

There could be a timing issue going on with your `ChildClass` child depending on when it's getting rendered. The focus trap won't get created by focus-trap-react unless it can find the node that the trap is supposed to use as its container. So if, say, `ChildClass` isn't defined until after the `FocusTrap` renders, you may need to use the `focusTrapOptions` prop to manually configure the trap instead of relying on the automatic behavior.

**Comment by sant123** [comment]
Is <ChildClass /> a functional component? If so you need to use forwardRef.

**Comment by stefcameron** [comment]
> Is `<ChildClass />` a functional component? If so you need to use forwardRef.

Thanks for pointing this out! This is also very important. See the docs about this: https://github.com/focus-trap/focus-trap-react?tab=readme-ov-file#children

**Comment by stefcameron** [comment]
I'm going to assume this was resolved and close it. LMK if that's not the case.
