### ISSUE TITLE
Tab doesn't cycle

### ISSUE THREAD

**Issue by GoudekettingRM** [focus-trap/focus-trap-react#1325]
**Description**
I added trap focus to my modal and i try to tab cycle through all buttons, but it gets stuck at the last one. If I add an empty `features` object (`features={{}}`) to my component, it does cycle. Unsure why. I assumed it was because of strict mode, but when I wanted to add a `focusTrapOptions` to the `<FocusTrap>` component with `active: true`, it told me it doesn't exist as a prop? 

Passing a number (like 30 / Features.ALL) doesn't work. 

Using Next14, react 18.

**Versions**
- Browser/OS verion(s) involved: Brave Version 1.68.141 Chromium: 127.0.6533.120, M1 Mac, Sonoma 14.6.1
- focus-trap-react version used: 10.2.3

**Sandbox**
Do not really have a lot of time to make one. If needed, I can try.

**Comment by stefcameron** [comment]
@GoudekettingRM Thanks for reaching out! `focusTrapOptions` should be a separate prop from the `active` prop. See the [index.d.ts](https://github.com/focus-trap/focus-trap-react/blob/master/index.d.ts) to clarify, or the README.

Otherwise, nothing comes to mind just on the surface without having a repro. But be forwarned, I'm stacked right now; it could be weeks before I can really be of help. Sorry. Maybe some of the demos can help as a reference point?

**Comment by GoudekettingRM** [comment]
Alright, it was all user error.... it had autoimported from `@headless/react` and that one does not work as intended, but once I import it from focus-trap-react as I wanted, no issues. Sorry for the bug scare!

**Comment by stefcameron** [comment]
No worries, and thank you for the follow up!
