### ISSUE TITLE
R19 support

### ISSUE THREAD

**Issue by timfishercs** [focus-trap/focus-trap-react#1343]
**Description**

R19 doesn't support `findDOMNode`, is there any plans to remove references to it?

Warning: findDOMNode is deprecated and will be removed in the next major release. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node         at FocusTrap (/.node_modules/focus-trap-react/dist/focus-trap-react.js:47:5)

**Versions**
- Browser/OS verion(s) involved:
- focus-trap-react version used: latest

**Sandbox**
Minimal reproduction in something like [CodeSandbox](https://codesandbox.io/):
- If you can repro it in [focus-trap](https://github.com/focus-trap/focus-trap), __even better__ as that will exonerate `focus-trap-react` which tries to just be a wrapper for the real library.
- If you can't repro it there, that's helpful too since it points to `focus-trap-react` as the culprit.

**Screen Capture**
Recording or screenshot of what you're seeing -- if the repro isn't sufficient to explain it.

**Comment by stefcameron** [comment]
@timfishercs Thanks for asking. This library's use of `findDOMNode` was long-since been removed (back in 2022), see #710 🎉 

I've been [casually](https://github.com/focus-trap/focus-trap-react/tree/react19) working on R19 support and, having reviewed all the upcoming changes, the only thing that really needs to be done is strip-out the `propTypes` and remove the dependency on the `prop-types` package since that will just be ignored now by R19.

The one thing I will do, however, as part of "supporting" R19 is cut a new major where I'll set the minimum supported version of React to `18.3.x` Right now, the minimum is _ancient_, back to R16, and that's too much to support going forward given R18 has been around for nearly 2 years already.

So for all intents and purposes, focus-trap-react should already be ready for R19 -- unless you're seeing something I'm not?

**Comment by timfishercs** [comment]
@stefcameron My apologies, there were sub packages using the older version. All the tests pass so I presume everything is ok, will verify. Nice work keeping it up to date!

**Comment by stefcameron** [comment]
Cool! Thanks for adding your resolution and closing the issue. 😀

**Comment by VercammenJens** [comment]
Hey @stefcameron, I am getting an error related to R19 (not a breaking error currently):
`Accessing element.ref was removed in React 19. ref is now a regular prop. It will be removed from the JSX Element type in a future release.`

Is this also something you are looking at?

**Comment by stefcameron** [comment]
@VercammenJens Thank you for pointing this out! It wasn't on my radar, but I've got it fixed in #1416 😄

**Comment by stefcameron** [comment]
@all-contributors add @VercammenJens for bug

**Comment by andreasvirkus** [comment]
Still getting the same warning with `11.0.4`

```
hook.js:608 Accessing element.ref was removed in React 19. ref is now a regular prop. It will be removed from the JSX Element type in a future release. Error Component Stack
    at div (<anonymous>)
    at FocusTrap2 (focus-trap-react.js?v=412be8de:814:9)
    at div (<anonymous>)
    at Modal (index.tsx:21:22)
```

**Comment by stefcameron** [comment]
@andreasvirkus That's a bit strange... The version detection mustn't be working then with whatever React version you're using. Can you confirm if that's the case?

**Comment by andreasvirkus** [comment]
Yarn cache played a trick on me and I wasn't truly testing with `11.0.4` it seems (I went to view the `node_modules` source for `ReactVerMajor` variable and it wasn't there, which led me to investigate further) – can confirm it's fixed ✔️ Apologies!
