### ISSUE TITLE
New containerElements option doesn't lend itself to React

### ISSUE THREAD

**Issue by zioth** [focus-trap/focus-trap-react#183]
My scenario: I want to limit focus to the child of `FocusTrap`, and a set of CSS selectors. Here's what my code has to look like:

```
export const MyFocusTrap = props => {
  const ref = React.useRef();
  const [dummy, setDummy] = React.useState();

  React.useEffect(() => {
    setDummy(Math.random());
  }, []);

  // `array` is my own array utils library.
  const elts = array.compact(array.flatten([
    props.containerCss.map(s => Array.from(document.querySelectorAll(s))),
    ref.current
  ]));

  return (
    <FocusTrapReact containerElements={elts}>
      <div ref={ref}>{props.children}</div>
    </FocusTrapReact>
  );
};
```

The issues I see are:
1. In order to include the child, I have to use a ref. I don't want that `div` to exist at all.
2. Because the ref is necessary, I have to use dummy state to force the component to render twice on mount. Otherwise, the ref wouldn't be added to the elements list. This is the biggest issue, because it causes a potentially significant performance hit.
3. `containerElements` must be HTMLElements, not selectors, so I have to do a lot of extra work to get them into the right format.

**Comment by stefcameron** [comment]
@zioth Thanks for illustrating your scenario. At first glance, I agree, it's not pretty...

@cgood92 Any thoughts?

I'll have to think about this.

With `containerElements` now, it strikes me that the `children` prop doesn't technically have to be required anymore since it's ignored when `containerElements` is provided, so you could technically have

```jsx
<>
  <FocusTrapReact containerElements={containerElements} />
  <div ref={ref1} />
  <div ref={ref2} />
  <div ref={ref3} />
</>
```
and then use an effect to set an internal `containerElements` state variable to each of those refs whenever any of them are not `.current === null`...

Would that work?

Actually, while the typings say `children` is required, the prop-types don't, so you should be able to try this without messing with the focus-trap-react code.

**Comment by cgood92** [comment]
That is a scenario I hadn't thought of.

Is this a pass-through component, where children just pass on through, and you don't have access to their refs?

I think the current API has some ways to accomplish this, and I can't think of a good looking API that would accommodate this easier, but open to it.  What suggestions do you have @zioth ?

**Comment by stefcameron** [comment]
At the least, we should fix the typings to reflect that `children` is optional so it's synced with the prop-types, and also because it really is optional now with the `containerElements` alternative.

**Comment by zioth** [comment]
Yes, it's a pass-through component in my case. If it weren't, that would only fix the least important issue (the ugliness of having an extra `div`).

The requirement of a `ref` (and the associated performance hit) could be fixed by combining `children` with `containerElements` in `focus-trap-react`. I haven't dug through your code though, so I'm not sure whether that alone would fix the performance issue, since you might still need a ref.

I guess the performance hit will go away if I make `FocusTrapReact` a sibling of my rendered code. I think I'll do that for now, while you figure out whether you want to make any change here.

The rest of my issues could only be fixed by allowing css selectors in `containerElements` - basically using something a lot like the code I wrote above in `focus-trap`. I don't know whether that's worth it or not. I guess it depends on what ends up as the most common use-case.

**Comment by zioth** [comment]
Wait, no. Using siblings won't fix the performance issue. I still need to update state to make this work, which will force a rerender. So if I could get only one improvement from this ticket, it would be including `children` in the `containerElements ` list automatically, inside of `focus-trap`.

**Comment by stefcameron** [comment]
@zioth Thanks for your comments. I'm still not getting why you need this dummy state variable to kick the render. Whenever I work with refs in React, I always have to use an effect because of their very nature, and just how React is built. React doesn't want a strong link between its declarative state in code, and its imperative state in the DOM. And because refs are objects that have a `current` property, on purpose, when React sets `current` after render, there's no re-render -- hence your dummy state, or the use of an effect to set some more meaningful state prop to then cause a re-render.

On the flip side, `focus-trap` wants to work with nodes. Right there, it's always going to be somewhat of a struggle and not super elegant with React...

I'm wondering why this wouldn't work if you declared a `containerElements` local state array, and then used your effect to update that array with the `current` values from your refs if/when they have been set by React? Then set `<FocusTrapReact containerElements={containerElements} />`. This all seems quite elegant (i.e. "normal" React with refs) to me, unless I'm missing something. I do apologize if I am. :)

It also really doesn't make sense to have a child element with a focus trap that uses `containerElements`. I think we should think of the trap either in terms of `containerElements` or in terms of that single child, not both.

If it's still not working out for some reason, then I think it would really help if you could provide a codesandbox.io reconstruction of your issue so I can see it and play with it.

**Comment by cgood92** [comment]
> This is the biggest issue, because it causes a potentially significant performance hit.

I hear you.  Not doing re-renders is definitely a plus.  But, when using ref's, I find I'm almost always doing a second re-render. 
 I don't stress about that too much of the time, because we are using memoized components and such.  I'd love to work on a project where we were worried that a component rendered twice... your app must be the fastest app alive - I'm jealous.

> containerElements must be HTMLElements, not selectors, so I have to do a lot of extra work to get them into the right format.

Are you saying you'd prefer a selector as the API?  By selector, you mean a string that we could throw into a `document.querySelector` type of a thing?  How would you make a selector for react elements that haven't been rendered yet?  And, does that way seem more "react" to you than using react refs?

Thanks for the discussion.  Just trying to button it up, as I'm anxious to get my bug patch out.

**Comment by cgood92** [comment]
On top of recreating the issue you're seeing @zioth, I'd love to hear a proposal about how to do it differently.  I see some of the problems you have listed, I'm just not sure I'm seeing what you are suggesting we do about it?

Thanks again.

**Comment by stefcameron** [comment]
If selectors are required, then 'findDOMNode()' is a problem. That's the reason we restricted the API to HTMLElements only, IIRC. The library was already using it, so it's not new. But we'd have to find a clever alternative...

**Comment by zioth** [comment]
Whether the problem is solved with my dummy state or the cleaner `containerElements` state that you suggest, there's a double-render issue. Here's what happens, unless I'm missing something (which is absolutely possible!)
* The component code is executed for the first time. The `div`'s ref has not been assigned yet.
* The component is mounted and rendered.
* Mounting sets `ref.current`. There are no side-effects, because setting a ref doesn't trigger a rerender or any effects.
* The `containerElements` prop is never updated.
* If we add an effect on mount, we can set state, which will trigger a rerender and set the `containerElements` prop.

So either `containerElements` is wrong until some parent component happens to trigger a rerender, or we render twice.

I _think_ you can avoid this by changing:
```
      const elements = containerElements ? containerElements : [element];
      this.setFocusTrapElements(elements);
```
to 
```
      const elements = containerElements ? [...containerElements] : [];
      element && elements.push(element);
      this.setFocusTrapElements(elements);
```

but then you'd be allowing `children` and `containerElements` to exist at the same time, which doesn't seem to be what you want.

As to the other issue I pointed out, I think your vision of the project should determine whether `containerElements` should allow selectors. It would be useful for me, but maybe not for other developers.

I'm fine with closing this ticket if these changes aren't the direction you want to go.

**Comment by stefcameron** [comment]
I wasn't suggesting that using a local `containerElements` state and assigning that to the `containerElements` prop was going to reduce the render count to 1. I don't think it's possible to reduce it to 1 given how refs work.

I think we're fighting against principles of React. The fact is, an effect is required in order to get to the element that React created and associated with a component declaration in JSX, and if you're going to use the `<FocusTrap />` component, when I really don't see a way around that. (For a class-based component, you're still stuck because you need a callback post-render to get the ref's `current` value.)

If you want to squeeze every last drop of performance out of it and avoid as many renders as possible, then I think you should be using `focus-trap` directly instead of trying to use it via `<FocusTrap />` and its current restrictions to refs for `containerElements`.

I created this sandbox with 2 traps and render counts. The solution with refs (trap 1) actually renders 4 times, not 2 (not sure if that's directly proportional to the number of refs, like 2 renders per ref, but it's > 1). The solution using `focus-trap` directly (trap 2, which uses 1 ref and 1 CSS selector) actually still renders 2 times, but that's 2 times _less_ than the other way.

https://codesandbox.io/s/focus-trapreact-containerelements-demos-v5ydi

At this point, I'm not inclined to include the child in `containerElements`. I'd rather be more conservative/cautious right now  and make it either/or rather than including everything and see if we get more feedback wanting to include the child. That's because while the code would need more refactoring to avoid `React.children.only()` which ends-up requiring a dummy child in `<FocusTrap />`, when you use `containerElements`, you're totally breaking out of the "confines" of the child as the single container. At this point, _any_ container _anywhere_ can be in the trap.

Going forward, I'd like to see the requirement to have a child be dropped so you could just declare `<FocusTrap containerElements={...} />` and get a working trap, or do `<FocusTrap>{child}</FocusTrap>` and also get a working trap. Either way, the trap activates when rendered, provided it gets at least one valid element.

But that would still require `HTMLElement`s, not CSS selectors, in `containerElements` because of `ReactDOM.findDOMNode()` that doesn't support CSS selectors. It'll see the selector as a string and will return you a text node with the string inside of it -- not what you'd expect. The alternative to `findDOMNode()`, [as React suggests](https://reactjs.org/docs/react-dom.html#finddomnode), is refs...

To enable the use of CSS selectors with a React wrapper, I think a context provider and hook would work very nicely. I'll need to explore that one further, but in my mind, I think it would work.

Anyway, this has been a good discussion! I hope those sandboxes help...

**Comment by zioth** [comment]
You could do what I did, and convert selectors to elements each time you need the data, but I understand your reasoning for avoiding that.

I used an observer and a custom hook to add and remove trapped elements. I thought of going the context route, but I felt like that would add too much of a structural requirement to components. It's probably the way to go if you want to integrate it into `focus-trap-react`.

I'm not sure why you're seeing 4 renders in your sandbox. I added a console.log(), and only got two outputs. Then I changed the global counter to a ref, and the UI displayed 2. So I think you get the same number of renders using the React and non-React version.

Anyway, should this ticket be closed?

**Comment by stefcameron** [comment]
Alright, thanks again, closing.
