### ISSUE TITLE
"No focusable element" error thrown if children are hidden.

### ISSUE THREAD

**Issue by thunderkid** [focus-trap/focus-trap-react#20]
I have a hidden dialog box wrapped in a `FocusTrap`. I make the dialog box visible at the same time that I activate the `FocusTrap`. This causes the error:

`index.js:163 Uncaught Error: You can't have a focus-trap without at least one focusable element`.

It seems that as the FocusTrap activates, it's upset that there isn't already a non-hidden focusable element, even though I'm trying to create one simultaneously. If I add a fake always-visible focusable element it stops complaining. But I don't want that in production.
My setup is basically this:
```
<FocusTrap active={showIt}>
	<input style={{visibility: "visible"}} tabIndex={0}/>     // FAKE focusable element makes it work.
	<div style={{visibility: showIt ? "visible" : "hidden"}}>
		<input style={{visibility: "inherit"}} tabIndex={0}/>
	</div>
</FocusTrap>
```

I don't think I can use `fallbackFocus` since none of the contained elements are focusable while they're hidden. Is there a way just to suppress this error from being thrown?
Thanks!

**Comment by davidtheclark** [comment]
How about putting your FocusTrap inside the `<div>`?

**Comment by thunderkid** [comment]
Tried that and it seems to give the same error.

(Also, even if that worked it wouldn't be ideal architecturally: For some use cases - such as a set of tabs, all of which are hidden except one - it could get messy to have to put a separate focus trap inside each tab instead of a single wrapper around the whole set.)

**Comment by davidtheclark** [comment]
@thunderkid: Sorry for the period of silence. I think I understand the problem here, but no solution pops into mind. 

> Is there a way just to suppress this error from being thrown?

The error is meaningful: it means you are giving the focus trap control of focus but it has nowhere to *put* that focus, which is a problem. So I don't think I'd go with this solution.

If you or someone else figures out how to solve your problem, I'm open to a PR.

**Comment by 0xF013** [comment]
it looks like it fails if it's activated by default in `componentDidMount()`. The reason for this is probably that the actual attachment is done asynchronously by React or that componentDidMount happens a tick before the redraw, meaning `tabbable.js` finds zero focusable elements (since they are either not in the DOM at that moment or hidden or I don't know. Changing that callback's code to 
```
      if (this.props.active) {
        setTimeout(() => this.focusTrap.activate());
      }
```
makes it work (hurray angular v1 solutions).

I suggest doing this in a fork in the meanwhile until I figure out what's up with React or I or someone else does a PR.

**Comment by davidtheclark** [comment]
One suggestion to consider here is to use the [focus-trap](https://github.com/davidtheclark/focus-trap) library directly, instead of this React wrapper. That way you can activate the focus-trap at the precise moment that works for you. I wonder if that would work for edge cases like this.

**Comment by liudonghua123** [comment]
I have faced the same problem while I was using `preact-material-components@1.5.4`, the dependences are strange.
```
D:\code\electron\epmd-master>npm ls focus-trap
epmd@0.1.0 D:\code\electron\epmd-master
`-- preact-material-components@1.5.4
  +-- @material/dialog@0.39.3
  | `-- focus-trap@2.4.6
  `-- @material/drawer@0.39.3
    `-- focus-trap@3.0.0
```

![image](https://user-images.githubusercontent.com/2276718/47896331-f2d8cf80-dea7-11e8-83ac-8da4ee3f5698.png)

**Comment by chrispcode** [comment]
As said in the previous commend in the lifecycle that you switch state, there are no actual elements rendered on screen. You can fix this by creating a second state property and giving it a timeout or immediate. You can still continue using the react wrapper, you just have to do something like this:
![image](https://user-images.githubusercontent.com/7029482/50145524-14541600-02b2-11e9-991f-f0c1f1d61ff4.png)

![image](https://user-images.githubusercontent.com/7029482/50145499-069e9080-02b2-11e9-983a-67704db9e4ca.png)

![image](https://user-images.githubusercontent.com/7029482/50145550-26ce4f80-02b2-11e9-8529-f8fb6861001e.png)

**Comment by walt-er** [comment]
Adapting @chrispcode's example to React hooks worked beautifully, since `useEffect` will file once we've already rendered our content.

```jsx
const SomeClass = (props) => {
	const { active } = props;
	const [focusTrapped, setFocusTrapped] = useState(false);

	useEffect(() => {
		setFocusTrapped(active);
	});

	return (
		<FocusTrap
			active={focusTrapped}
		>
			...
		</FocusTrap>
	);
}
```

**Comment by stefcameron** [comment]
I'm not sure what the code of `focus-trap-react` looked like 3 years ago when this issue was first reported, but now there are props to control if/when the trap gets activated, which hopefully helps toward this problem. But the folks here are correct about the root cause, which is related to timing of when React updates the DOM, and when the focus trap tries to activate. The underlying `focus-trap` library relies on the DOM (imperatively) while React is just a declarative language, so it's a bit tricky to go from the declarative (what you intend to have happen) to the imperative (nodes in the DOM).

**Comment by StamatisDeli** [comment]
For my case, it was about assigning the focus ref to one of my custom containers
