### ISSUE TITLE
Support React 17

### ISSUE THREAD

**Issue by mquandalle** [focus-trap/focus-trap-react#356]
NPM v7 throws the following error when using focus-trap-react with the latest version of React:

```
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.0" from the root project
npm ERR!   peer react@">=16.0.0" from focus-trap-react@8.5.0
npm ERR!   node_modules/focus-trap-react
npm ERR!     focus-trap-react@"^8.5.0" from the root project
```

For reference, I had a similar problem with another package, cf. https://github.com/diegomura/react-pdf/issues/1062

**Comment by stefcameron** [comment]
Interesting. I haven't noticed this, though I tend to use yarn more than npm to install/manage dependencies.

Our package.json does state:
```
    "react": ">=16.0.0",
    "react-dom": ">=16.0.0"
```

That should cover React 17, 18 , ... and beyond right now.

https://github.com/diegomura/react-pdf/issues/1062#issuecomment-813804883 is pointing to `npm@7` as the culprit, which makes sense because according to [NPM Ranges](https://docs.npmjs.com/cli/v7/using-npm/semver#ranges), the syntax above should work...

Perhaps it would be better if we expressed the range as an OR?

```
    "react": "^16.0.0 || ^17.0.0",
    "react-dom": "^16.0.0 || ^17.0.0",
```

**Comment by stefcameron** [comment]
I assume this has been solved. Closing. LMK if that's not the case! :)
