### ISSUE TITLE
FocusTarget Typing Suggestion

### ISSUE THREAD

**Issue by dziul** [focus-trap/focus-trap-react#452]
version: `"focus-trap-react": "^8.7.1"`

I recently needed to use `focusTrapOptions.initialFocus`

> `initialFocus?: FocusTarget | false;`

I tried using `HTMLDivElement`, but I got an error. Looking at _global.d.ts_, `HTMLDivElement` extends `HTMLElement`, so the suggestion would be to add a generic type, eg:

```ts
export type FocusTarget<T extends HTMLElement> = T | SVGElement | string | { (): T | SVGElement };
```

so that all elements that are extended from `HTMLElement` be accepted.

**Comment by stefcameron** [comment]
@dziul Thanks for suggesting this. It does make sense, though I wonder about `SVGElement` in there. Also, there's a pending change for `initialFocus` typings that will soon be published:

```
export type FocusTargetOrFalse = HTMLElement | SVGElement | string | false | (() => HTMLElement | SVGElement | false);
...
initialFocus?: FocusTargetOrFalse;
```

I just discovered that TypeScript DOM types define a `HTMLOrSVGElement` type: https://github.com/microsoft/TypeScript/blob/main/lib/lib.dom.d.ts#L7859

Maybe we should extend from that instead?

```
export type FocusTargetOrFalse<T extends HTMLOrSVGElement> = T | string | false | (() => T | false);
```

**Comment by stefcameron** [comment]
Note this is a change that would need to go into https://github.com/focus-trap/focus-trap, not this library.

**Comment by dziul** [comment]
> @dziul Thanks for suggesting this. It does make sense, though I wonder about `SVGElement` in there. Also, there's a pending change for `initialFocus` typings that will soon be published:
> 
> ```
> export type FocusTargetOrFalse = HTMLElement | SVGElement | string | false | (() => HTMLElement | SVGElement | false);
> ...
> initialFocus?: FocusTargetOrFalse;
> ```
> 
> I just discovered that TypeScript DOM types define a `HTMLOrSVGElement` type: https://github.com/microsoft/TypeScript/blob/main/lib/lib.dom.d.ts#L7859
> 
> Maybe we should extend from that instead?
> 
> ```
> export type FocusTargetOrFalse<T extends HTMLOrSVGElement> = T | string | false | (() => T | false);
> ```



interesting, since `HTMLElement` and `SVGElement` extend this `HTMLOrSVGElement`

**Comment by dziul** [comment]
> Observe que essa é uma mudança que precisaria ir para https://github.com/focus-trap/focus-trap , não para esta biblioteca.

In this case, would I need to open this same issue in this library?

**Comment by stefcameron** [comment]
> interesting, since `HTMLElement` and `SVGElement` extend this `HTMLOrSVGElement`

They also both extend just `Element`. I'm not sure what's best here, though. I don't use TypeScript enough to know the difference.

**Comment by stefcameron** [comment]
> > Note this is a change that would need to go into https://github.com/focus-trap/focus-trap, not this library.
> 
> In this case, would I need to open this same issue in this library?

No, I think we can discuss here. Just pointing out that the fix will ultimately be over there instead of in here.

**Comment by dziul** [comment]
> > interesting, since `HTMLElement` and `SVGElement` extend this `HTMLOrSVGElement`
> 
> They also both extend just `Element`. I'm not sure what's best here, though. I don't use TypeScript enough to know the difference.


Here would be the `HTMLElement`, which refers to an HTML element. And He extends the `Element`, which extends the `Node`. 😅

**Comment by stefcameron** [comment]
> > > interesting, since `HTMLElement` and `SVGElement` extend this `HTMLOrSVGElement`
> > 
> > 
> > They also both extend just `Element`. I'm not sure what's best here, though. I don't use TypeScript enough to know the difference.
> 
> Here would be the `HTMLElement`, which refers to an HTML element. And He extends the `Element`, which extends the `Node`. 😅

Actually, I was thinking about this more, and I think `HTMLOrSVGElement` would be the right thing to use, because what we're really after is a focusable element, thus one that has the `focus()` method:

```
interface HTMLOrSVGElement {
    readonly dataset: DOMStringMap;
    nonce?: string;
    tabIndex: number;
    blur(): void;
    focus(options?: FocusOptions): void;    // <- this!
}
```

So I'm thinking we should go with:
```
export type FocusTargetOrFalse<T extends HTMLOrSVGElement> = T | string | false | (() => T | false);
```

**Comment by dziul** [comment]
> Actually, I was thinking about this more, and I think `HTMLOrSVGElement` would be the right thing to use, because what we're really after is a focusable element, thus one that has the `focus()` method:
> 
> ```
> interface HTMLOrSVGElement {
>     readonly dataset: DOMStringMap;
>     nonce?: string;
>     tabIndex: number;
>     blur(): void;
>     focus(options?: FocusOptions): void;    // <- this!
> }
> ```
> 
> So I'm thinking we should go with:
> 
> ```
> export type FocusTargetOrFalse<T extends HTMLOrSVGElement> = T | string | false | (() => T | false);
> ```



I agree, `HTMLOrSVGElement` is the best scenario.

**Comment by stefcameron** [comment]
If I make this change, I get TSC errors like this:
```
index.d.ts:83:20 - error TS2314: Generic type 'FocusTargetOrFalse' requires 1 type argument(s).

83     initialFocus?: FocusTargetOrFalse;
```

So the type for the `initialFocus` option would then have to change to:
```
initialFocus?: FocusTargetOrFalse<SOMETHING?>;
```

I'm not sure what to put there. Seems like I'd have to specify a type, and then we're right back where we started.

Come to think of it, I'm surprised the current definition of
```typescript
export type FocusTargetOrFalse = HTMLElement | SVGElement | string | false | (() => HTMLElement | SVGElement | false;
```
is causing you trouble when you try to give an `HTMLDivElement` to a property like `initialFocus`. As you said earlier, `HTMLDivElement` extends from `HTMLElement`, so there should be no type issue with giving this type of element to the option. `HTMLDivElement` is compatible with `HTMLElement` in terms of interfaces since `HTMLDivElement is a superset of `HTMLElement`.

So why is this a problem at all? 🤔

**Comment by dziul** [comment]
Yeah, I'm sorry I sell now, there's no problem as it is.   The problem is that I'm using refs, and it's `HTMLDivElement|null` and when I forced the type with `as HTMDivElement`, it had raised an error. But now everything is ok. I believe that at the time it was late in the eslint

**Comment by stefcameron** [comment]
> Yeah, I'm sorry I sell now, there's no problem as it is. The problem is that I'm using refs, and it's HTMLDivElement|null and when I forced the type with as HTMDivElement, it had raised an error. But now everything is ok. I believe that at the time it was late in the eslint

OK, cool. Thanks for confirming.

> in this the suggestion would be to add `null` to `FocusTarget`

That would cause an error in focus-trap, however, since the options that use the `FocusTarget` type do not accept `null` as a value. The option can be `undefined` (not set) or it can be `false` (explicitly state that set focus should not happen). But `null` is what results if you give it a `string` and we evaluate that selector and it's an invalid selector.

Still, if you have declared that the type of your ref is `HTMLDivElement`, and we've established that `HTMLDivElement` extends from `HTMLElement`, and the `initialFocus` option is typed such that it can be a function that returns an `HTMLElement`, then why can't TypeScript automatically figure-out that your ref is compatible? -- Ah, probably because the type of the ref is some type that also allows any other value.

Hmm, I'm not sure if there's a good alternative here, other than maybe `initialFocus: () => containerRef.current || false` since if `initialFocus()` is called before your ref is assigned to its node, returning `null as HTMLDivElement` will still be `null`, and will cause an exception in focus-trap. You're better-off returning `false` in that case.

**Comment by dziul** [comment]
> Hmm, I'm not sure if there's a good alternative here, other than maybe initialFocus: () => containerRef.current || false since if initialFocus() is called before your ref is assigned to its node, returning null as HTMLDivElement will still be null, and will cause an exception in focus-trap. You're better-off returning false in that case.

I agree, so in this case I would change it to:

```ts
type HTMLElementOrSVGElementOrFalse = HTMLOrSVGElement | false
export type FocusTarget = HTMLOrSVGElement | string | {(): HTMLOrSVGElement};


Export interface options {

...
initialFocus ?: FocusTarget;
...

}

```

thus, we would be able to use `() => (ref.current || false)`.

Since in my case, I have to use a _function_, if I pass directly to _ref DOM_, it doesn't work

**Comment by stefcameron** [comment]
OK, great! So that's basically what we have now (just hasn't been published yet because there are a few changes in flight still that I'm waiting on to be done). See https://github.com/focus-trap/focus-trap/blob/master/index.d.ts#L14

**Comment by stefcameron** [comment]
Once the other focus-trap changes are merged, I'll publish focus-trap and then publish focus-trap-react to update its dependency on focus-trap, and then you'll have all the right typings.
