### ISSUE TITLE
Seeking co-maintainers!

### ISSUE THREAD

**Issue by davidtheclark** [focus-trap/focus-trap-react#48]
I've been shifting my focus away from UI development, so don't plan on addressing new issues myself. If you use this library and want to see development continue, you can make that happen by becoming a co-maintainer — with permissions to triage issues, merge PRs, cut releases, etc.

Please comment below if you're interested!

Another possibility is for a dedicated owner to fork this code and create a new package. I'd be happy to link to that library from the README of this one.

**Comment by nahumzs** [comment]
Hey, @davidtheclark here at  [galvanize](https://www.wegalvanize.com/) would like to help you with the react repo if you want to, we are currently using it for the next version of our [UI](https://github.com/acl-services/paprika). 

For us would work better if we can fork this repo and created a new package from it.

**Comment by davidtheclark** [comment]
> For us would work better if we can fork this repo and created a new package from it.

Sure, @nahumzs. Feel free to file a PR adding a link to this repo's README.

**Comment by theKashey** [comment]
Meanwhile, https://github.com/reactjs/rfcs/pull/109 and [react-events](https://github.com/facebook/react/tree/master/packages/react-events), as a focus managed bundled inside React, are going to make this package obsolete.

**Comment by wldcordeiro** [comment]
🤚 @davidtheclark could I get collaborator here as well? Trying to do a synced update across the chain to `react-aria-modal` 😄

**Comment by toolness** [comment]
Ditto to what @wldcordeiro said--I now have collaborator access to react-aria-modal but it'd be nice to be able to fix https://github.com/davidtheclark/focus-trap-react/issues/24, which would also allow me to add tests to react-aria-modal.

**Comment by maraisr** [comment]
Is there still a call for maintainers?

**Comment by stefcameron** [comment]
@davidtheclark This project, as well as focus-trap and tabbable, are really useful. I'd like to give a try to helping maintain this one. I'm `stefcameron` over on NPM as well, for publishing purposes.

**Comment by stefcameron** [comment]
@davidtheclark Thanks for upgrading me to contributor so I can merge PRs. Looking at the PRs, there are a number from Dependabot which I'd like to merge. There are also a few other PRs I'd merge right away also, related to dependencies and some bugs. So I would do this:

- Merge #71 
- Merge #72 
- Merge #66 
- Merge #67 
- Merge #55 
- add `prettier --check` to the `test` script to fail tests if prettier hasn't been run on changes
- Just bump all dependency versions to their latest versions and see if things still work since dependencies haven't been updated in a long time.

After all that, I would want to publish a new major. Too many changes to chance a minor.

Should I just go ahead and start merging stuff at will?

Do you have a set process to follow for publishing? I noticed a [commit](https://github.com/davidtheclark/focus-trap-react/commit/69c14950c427eddbee14550358ec516459cb0ba1) from you a long time ago where you had `HEAD` in the CHANGELOG and then you updated that to `6.0.0` manually. Is that just a pattern you follow, adding things to the CHANGELOG under `HEAD` until you're ready to publish a new version?

When you publish, do you publish manually from your system or some other way through CI somewhere? I see integration with TravisCI, but that looks like it's just for running tests.

**Comment by davidtheclark** [comment]
> Should I just go ahead and start merging stuff at will?

Yes, feel free to take the reins.

> I noticed a commit from you a long time ago where you had HEAD in the CHANGELOG and then you updated that to 6.0.0 manually. Is that just a pattern you follow, adding things to the CHANGELOG under HEAD until you're ready to publish a new version?

Yes, that's how I typically do it.

> When you publish, do you publish manually from your system or some other way through CI somewhere?

I've been publishing manually from my computer with `npm publish`.

**Comment by stefcameron** [comment]
@davidtheclark Perfect, thank you! 👍

**Comment by stefcameron** [comment]
@davidtheclark Hey, so I've made a bunch of updates and merged a few PRs per the plan I shared with you a couple of weeks ago. Did you ever give me permission to publish on NPM? We're ready for 7.0.0 (because of breaking changes).

**Comment by davidtheclark** [comment]
@stefcameron yes, you have access to publish on npm.

**Comment by maraisr** [comment]
@stefcameron what do you think about setting up https://github.com/atlassian/changesets? @davidtheclark has given me write access also; so was going to push up some sort of CI using GH Actions to handle these publishes.

**Comment by stefcameron** [comment]
@maraisr Interesting you bring that up! I noticed this project a few weeks ago and took note of it. I've been curious about how it works in practice since it seems quite handy in theory. I'd like to publish 7.0.0 tomorrow so as not to delay any longer, but if you know how to set that all up, let's give it a try for future changes/releases! Sounds good?
