### ISSUE TITLE
IE11 focus is not trapped when SVG is first focusable element

### ISSUE THREAD

**Issue by vientang** [focus-trap/focus-trap-react#65]
Inside of FocusTrap, I've set an svg to be the initial focusable element. However, this doesn't trap the focus, which means that the elements in the background are tabbable. This is only in IE11 (wish I didn't have to work with IE11 trust me). 

For brevity, here's a basic composition. The "dialog" div is appended to the body tag.
`<FocusTrap><div id="dialog"><svg focusable tabIndex="0"> ...  </svg></div></FocusTrap>`

By doing this, I can verify in the DOM in IE11 that the svg does have the tabIndex="0" and focusable="true". But the focus is not trapped and I cannot reach the svg by tabbing.

I can work around this by putting the initial focus on the "dialog" div instead. This traps the focus correctly and the svg is in the tab flow. Curious to know if anyone has insight as to why focus isn't trapped if an svg is the initial focusable element.

**Comment by stefcameron** [comment]
@vientang Catching up as a new maintainer. Thank you for logging this issue! This sounds like more of a [focus-trap](https://github.com/focus-trap/focus-trap) issue than `focus-trap-react`, but unsure if it's still an issue, and unfortunately, I don't have access to IE11 to test it out. But given no one else has commented here, or reacted with a thumbs up, I'm going to close this. If it's still a problem, I think a new issue should be opened on `focus-trap` instead of here if it can be reproduced there.
