### ISSUE TITLE
setReturnFocus's previouslyActiveElement is undefined, and returning false yields "setReturnFocus did not return a node"

### ISSUE THREAD

**Issue by Slapbox** [focus-trap/focus-trap-react#705]
Thanks for the great work on this library! Seeing two unexpected errors in `setReturnFocus` with `focus-trap-react@8.11.2`.

Code like below:

```js
 <FocusTrap
  focusTrapOptions={{
    setReturnFocus: previouslyActiveElement => {
      console.log(typeof previouslyActiveElement) // undefined
      return false;
    },
  }}>
```

@stefcameron, any ideas?

**Comment by stefcameron** [comment]
Yes, I think it's because focus-trap-react has to do some special handling of some of the deactivation options of focus-trap (because of how React works), and it looks like it's not aware that it's supposed to pass the previously active element to the `setReturnFocus` option-as-a-function: https://github.com/focus-trap/focus-trap-react/blob/master/src/focus-trap-react.js#L110

Thanks for this (and the query over on focus-trap), I'll try to get a fix out for this shortly.

**Comment by stefcameron** [comment]
Fix coming in #706 🙂

**Comment by Slapbox** [comment]
Holy cow that was fast! Huge thanks @stefcameron! I'll keep an eye out for a new release soon.

**Comment by stefcameron** [comment]
My pleasure! Yes, release will come soon.

**Comment by stefcameron** [comment]
BTW, your inquiry here surfaced a bug with focus-trap typings related to `initialFocus`, `fallbackFocus`, and `setReturnFocus` which were all missing a possible return type of `string` when they're functions since it's also possible to return a selector string from any of these.

**Comment by stefcameron** [comment]
Will be in v8.11.3 which will be published in ~5 minutes.

**Comment by stefcameron** [comment]
@all-contributors add @Slapbox for bug
