### ISSUE TITLE
Doesn't work if child of FocusTrap is React component created using classes

### ISSUE THREAD

**Issue by bondom** [focus-trap/focus-trap-react#773]
This example works correctly:
```
  <FocusTrap>
    <div>
      <button>Btn</button>
     </div>
  </FocusTrap>
```

This example doesn't work:

```
class Test extends Component {
    render() {
        return <div><button>Btn</button></div>;
    }
}
  <FocusTrap>
    <Test />
  </FocusTrap>
```

Error that is returned: TypeError: el.querySelectorAll is not a function

<img width="730" alt="image" src="https://user-images.githubusercontent.com/18090218/184357058-52f6ab79-d809-4d1b-afe4-c6c1dc271181.png">

Link to playground: https://playcode.io/940558/

**Comment by stefcameron** [comment]
🤔 Does it work with a functional component instead of a class component? I'm kind of surprised, but not surprised, because focus-trap-react is always in tension between React's declarative API and tabbable's imperative expectations. Or maybe what we have here is some type of ref issue and we end-up passing the React element instead of the DOM element down to tabbable to get candidates.

**Comment by bondom** [comment]
Yep, it works with functional component

**Comment by stefcameron** [comment]
Interesting, thanks for checking that.

**Comment by stefcameron** [comment]
Looking into this further, I don't think it's possible to use a class-based component as the single child of `<FocusTrap>` because the trap requires a ref to the child, and React doesn't provide a way to forward a ref to a class-based component. Refs can only be forwarded with `React.forwardRef()` -- as you seem to have discovered since your sandbox uses `forwardRef()` on the functional component test you added (and it works).

Now, it's possible to "forward" a ref through a class-based component by taking the ref and assigning it to some other property name like "forwardedRef", but that would require focus-trap-react to set its callback ref on this specially-named prop when it [clones the child](https://github.com/focus-trap/focus-trap-react/blob/4d8e041b98c51dfba6f983b7010ce158d08f3e77/src/focus-trap-react.js#L405), which could collide with a prop name the person using the package wants to (or needs to) use on the class-based component they're giving to `<FocusTrap>`. And it would also require a special call out to warning people trying to use a class-based component as the trap's single child that they need to have their child accept this prop and set it on the root element they render from it.

And I don't think that's really any better (actually, I think it's worse, because of the possible special ref forwarding prop name collision) that simply calling out in the README that if you're going to provide a component as the child, it must be a __ref-forwarding functional component__.

**Comment by stefcameron** [comment]
FYI #781 will update the README with a note about this, and a working example. Please LMK if you think it's good or if there's something you think is missing.

**Comment by stefcameron** [comment]
I think there might be a work around where you could use the `containerElements` prop. When that prop is specified (and it an empty array should be supported by the code), the single child is ignored as far as using it as the container element. It'll still be rendered, just not used for the trap itself. Then get your own ref to your single class-based child, and once you have it, update your `containerElements` prop to be an array with a single element in it, that being the element React created for your class-based single-child container.

LMK if you try it and if it works. I think it will.
