### ISSUE TITLE
How to avoid initial focus on Focus-Trap?

### ISSUE THREAD

**Issue by cristianofmc** [focus-trap/focus-trap-react#815]
I implement a base code of focus-trap to open my modal and disable the trap when I close the modal

When I use the mouse to open my modal, the first button already appears with focus (the ring that only appears when I use the keyboard).
![image](https://user-images.githubusercontent.com/27186405/190308783-013ff7ee-6aa8-42a6-a448-a5d003dc6953.png)

To try to solve this I added initialFocus: 'false':

```
<FocusTrap focusTrapOptions={{ initialFocus: 'false', onDeactivate: onClose}} >
  <div>
  ...
  </div>
<FocusTrap>
```
But I end up getting this error as soon as the modal opens.
![image](https://user-images.githubusercontent.com/27186405/190308720-1e5248f4-130e-4a20-87ff-d0e904e7ef62.png)

What would be the best approach to avoid that?

**Comment by stefcameron** [comment]
@cristianofmc If I update the [defaults demo](https://focus-trap.github.io/focus-trap-react/demo/) (first one at the top) to use `initialFocus: false`, I get a trap that, when active, does not set initial focus to anything... So I can't reproduce your issue.

What version of focus-trap are you using? I suspect you're using an old version that doesn't support the `false` option since that was added somewhat recently-ish in the library's history.

**Comment by cristianofmc** [comment]
thanks @stefcameron , my bad I changed 'false' to just false and it's worked

**Comment by stefcameron** [comment]
My pleasure! Glad it was an easy solution. 🙂
